version: "3"

services:
  nginx:
    image: nginx:1.10-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3001:80
    depends_on:
      - backend
  backend:
    image: hitode909/secure-plains-1667
    command: carton exec -- plackup -E production -s Starlet -p 3000
